# This file is part of simple-crosshair-overlay and is licenced under the GNU GPL v3.0.
# See LICENSE file for full text.
# Copyright © 2023 Michael Ripley

name: Publish
on:
  workflow_dispatch:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Setup workflow cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install extra Linux dependencies
        run: | # gdk-sys needs {libgtk-3-dev}.
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libpango1.0-dev
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
